# Generated by Django 6.0.2 on 2026-02-04 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='member_id',
            field=models.CharField(editable=False, max_length=20, unique=True),
        ),
    ]
