# Generated by Django 6.0.2 on 2026-02-04 19:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_alter_member_member_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='public_id',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
    ]
