# Generated by Django 6.0.2 on 2026-02-14 19:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_member_address_member_blood_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='phone',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='เบอร์โทรต้องเป็นตัวเลข 9-15 หลักเท่านั้น', regex='^[0-9]{9,15}$')]),
        ),
    ]
