# Generated by Django 6.0.2 on 2026-02-14 19:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_alter_member_phone_validators'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['public_id'], name='members_mem_public__30307c_idx'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['member_id'], name='members_mem_member__1c9876_idx'),
        ),
    ]
