# Generated by Django 6.0.2 on 2026-02-28 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_add_member_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
